#!/bin/bash

IDIR="${BASH_SOURCE%/*}"
if [[ ! -d "$IDIR" ]]; then IDIR="$PWD"; fi
source "$IDIR/inc/misc_tools.sh"

# Edit the following locations to provide the
TMUX=`which tmux`
if [ -z $TMUX ]; then
    TMUX=/usr/local/bin/tmux
fi

# No need to edit below this line unless you find a bug!

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF
Shows the background terminals of with the given tmux-id and terminal-num
running in the docker machines.

Usage: djamterm [tmux-id] [-t terminal-num]

This is the docker version of the jamterm command.

djamterm
Shows the first C terminal of the program that was last started.

djamterm -t 2
Shows the second C terminal of the program that was last started.

djamterm u-600-dev-2331-c -t 2
Shows the second C terminal of the program running under u-600-dev-2331.

djamterm u-600-dev-2331-c
Shows the first C terminal of the program running under u-600-dev-2331.

djamterm u-600-dev-2331-j
Shows the J terminal of the program running under u-600-dev-2331.

EOF
}

localtmux() {
    local tmuxapp=$1
    local termno=$2

    $TMUX has-session -t $tmuxapp 2>/dev/null
    res=$?
    if [ $res == "0" ]; then
        if [ -z $termno ]; then
            $TMUX attach -t $tmuxapp
        else
            $TMUX attach -t $tmuxapp-$termno
        fi
    fi
}

dockertmux() {
    local tmuxapp=$1
    local termno=$2
    local appsfolder="$HOME/.jamruns/apps"

    for appdir in "$appsfolder"/*/; do
        for instance in "$appdir"*/; do
            if [[ -f "$instance/class" && "$(tr -d '[:space:]' < "$instance/class")" == "docker" ]]; then
                local docker_id
                docker_id=$(tr -d '[:space:]' < "$instance/dockerId")

                # Check tmuxid_c (device C nodes)
                if [[ -f "$instance/tmuxid_c" ]]; then
                    local dtm_c
                    dtm_c=$(tr -d '[:space:]' < "$instance/tmuxid_c")
                    if [[ "$dtm_c" == "$tmuxapp" ]]; then
                        # echo "Match found (Device). Attaching to $tmuxapp in $docker_id"
                        attach_tmux_in_docker "$docker_id" "$tmuxapp" "$termno"
                        return 0
                    fi
                fi

                # Check tmuxid (cloud/fog J nodes)
                if [[ -f "$instance/tmuxid" ]]; then
                    local dtm_j
                    dtm_j=$(tr -d '[:space:]' < "$instance/tmuxid")
                    if [[ "$dtm_j" == "$tmuxapp" ]]; then
                        # echo "Match found (Cloud/Fog). Attaching to $tmuxapp in $docker_id"
                        attach_tmux_in_docker "$docker_id" "$tmuxapp" "$termno"
                        return 0
                    fi
                fi
            fi
        done
    done

    # echo "No matching tmux session found for tmux-id: $tmuxapp"
    return 1
}


attach_tmux_in_docker() {
    local docker_id=$1
    local tmuxapp=$2
    local termno=$3

    if [[ -t 1 ]]; then
        if [ -z "$termno" ]; then
            docker exec -it $docker_id tmux attach -t $tmuxapp
        else
            docker exec -it $docker_id tmux attach -t "$tmuxapp-$termno"
        fi
    else
        echo "Tmux session '$tmuxapp' is running inside the container '$docker_id'."
        echo "You can attach manually using:"
        echo "docker exec -it $docker_id tmux attach -t $tmuxapp"
    fi
}

###
# Main script execution begins here...
#

jamfolder=$HOME"/.jamruns"
exit_missingdir $jamfolder ".jamruns folder missing. JAMScript tools not setup?"

appsfolder=$jamfolder/apps
exit_missingdir $appsfolder ".jamruns/apps folder missing. JAMScript tools not setup?"

cd $appsfolder

if [ -z $1 ]; then
    if [ -e tmuxid ]; then
        tmuxid=`cat tmuxid`
        dockertmux $tmuxid
        exit
    fi
else
    if [ $1 == "-h" ] || [ $1 == "--help" ]; then
        show_usage
        exit
    elif [ $1 == "-t" ]; then
        if [ -e tmuxid ]; then
            tmuxid=`cat tmuxid`
            dockertmux $tmuxid $2
        fi
        exit
    else
        if [ -z $2 ]; then
            txid=$1
            if [[ ${txid: -1} == "c" || ${txid: -1} == "j" ]]; then
                dockertmux $txid
            else
                localtmux $txid
            fi
            exit
        else
            if [ -n $3 ] && [ $2 == "-t" ]; then
                termid=$3
                dockertmux $1 $termid
            fi
        fi
    fi
fi