#!/bin/bash


IDIR="${BASH_SOURCE%/*}"
if [[ ! -d "$IDIR" ]]; then IDIR="$PWD"; fi
source "$IDIR/inc/misc_tools.sh"

die() {
    printf '%s\n' "$1" >&2
    exit 1
}

show_usage() {
    cat << EOF
A tool to display the active programs and their attributes.
Usage: djamlist 

djam list [--help]

djam list [--all]
    
djam list [--monitor]

djam list [--remote]

djam list [--type==fog]

djam list [--dataStore==127.0.0.1:21883]

djam list [--tmuxid==tg-25165]

djam list [--port=3]
   
djam list [--app==XX3]

djam list [--prog==X]


This is the docker version of jamlist.

EOF
}
 
runjamist(){
    local didp=`docker ps | awk 'NR > 1 {print $1; exit}'`
    echo $didp
    docker exec -it $didp jamlist
}
runjamist

