- name: Start JAMScript Server and Run JAMRun Command
  hosts: "{{ server }}"
  gather_facts: no
  tasks:
    - name: Ensure the working directory is correct
      shell: pwd
      args:
        chdir: /home/jamtools/JAMScript/tools

    - name: Start the server (Express API) in the background
      shell: nohup node app-docker.js > server.log 2>&1 &
      args:
        chdir: /home/jamtools/JAMScript/tools
      async: 10
      poll: 0

    - name: Wait for the server to initialize
      pause:
        seconds: 5

    - name: Run JAMRun command and store logs
      shell: zx wrapper.mjs jamrun "{{ file }}" "{{ app }}" --bg > jamrun.log 2>&1
      args:
        chdir: /home/jamtools/JAMScript/tools

    # - name: Run JAMKill
    # shell: zx wrapper.mjs jamkill
    #  args:
    #     chdir: /home/jamtools/JAMScript/tools
