- name: Run JamTerm command
  hosts: "{{ server }}"
  gather_facts: no
  tasks:
    - name: Ensure the working directory is correct
      shell: pwd
      args:
        chdir: /home/jamtools/JAMScript/tools

    - name: Run JAMTerm with or without tmux param, and log output
      shell: >
        {
          {{ 'zx wrapper.mjs jamterm ' ~ tmux if tmux is defined else 'zx wrapper.mjs jamterm' }}
        } > jamterm.log 2>&1
      args:
        chdir: /home/jamtools/JAMScript/tools
